### ISSUE TITLE
Add "how it's different" to the README

### ISSUE THREAD

**Issue by jhelwig** [lipanski/datadog-sidekiq#1]
Might be worth adding a section to the README that explains why someone might want to use this instead of (or in addition to) using the `redis.key.length` metric that comes from the Redis integration in the DataDog agent (http://docs.datadoghq.com/integrations/redis/) when it's configured to monitor specific keys?

**Comment by lipanski** [comment]
https://github.com/lipanski/datadog-sidekiq#alternative

thanks for the suggestion :1st_place_medal:
